language: node_js
node_js:
  - 6.9.5
script:
  - "npm install"
  - "npm install -g angular-cli"
  - "ng build --prod"
deploy:
  provider: npm
  email: "vsnrakesh.u@gmail.com.com"
  api_key: "455c844d-cdc5-488c-a76f-e15d344a3dc6"
  on:
    tags: true
    branch: develop
  skip_cleanup: true
